#!/usr/bin/env bash
# scripts/build-knowledge-index.sh
#
# Regenerate knowledge/INDEX.md by scanning all files in knowledge/ (top
# level + immediate subdirs, excluding archive/). Pulls first H1 as
# one-liner, last git commit date, and file size.
#
# Triggered automatically by post-knowledge-edit hook on every Edit/Write
# touching knowledge/ (except INDEX.md itself).
#
# Idempotent — safe to re-run.
#
# Usage:
#   bash scripts/build-knowledge-index.sh          # write to knowledge/INDEX.md
#   bash scripts/build-knowledge-index.sh --dry    # stdout only, no file write
#
# Configuration (env vars or governance.config.yaml — see docs/governance.md):
#   GIOVANNI_CONSTITUTION_FILE  filename of constitution within knowledge/
#                               (default: constitution.md). Used to mark
#                               the constitution row in cross-references.
#   GIOVANNI_KNOWLEDGE_DIR      relative path to knowledge dir from repo root
#                               (default: knowledge)

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPO_ROOT="$( cd "${SCRIPT_DIR}/.." && pwd )"
KNOWLEDGE_DIR="${GIOVANNI_KNOWLEDGE_DIR:-knowledge}"
KNOWLEDGE="${REPO_ROOT}/${KNOWLEDGE_DIR}"
INDEX="${KNOWLEDGE}/INDEX.md"
CONSTITUTION_FILE="${GIOVANNI_CONSTITUTION_FILE:-constitution.md}"
DRY=0
[ "${1:-}" = "--dry" ] && DRY=1

if [ ! -d "${KNOWLEDGE}" ]; then
    echo "ERROR: knowledge dir not found: ${KNOWLEDGE}" >&2
    exit 1
fi

cd "${REPO_ROOT}"

# ----- helpers -----

human_size() {
    local bytes="${1:-0}"
    if [ "${bytes}" -gt 1048576 ]; then
        awk "BEGIN { printf \"%.1fM\", ${bytes} / 1048576 }"
    elif [ "${bytes}" -gt 1024 ]; then
        awk "BEGIN { printf \"%dK\", ${bytes} / 1024 }"
    else
        echo "${bytes}B"
    fi
}

first_h1() {
    local f="$1"
    local h1
    h1=$(grep -m1 -E '^# [^#]' "${f}" 2>/dev/null | sed 's/^# *//' | head -c 110)
    if [ -z "${h1}" ]; then
        # Fall back to first non-blank, non-frontmatter line
        h1=$(awk '
            /^---$/ { fm = !fm; next }
            !fm && NF { print; exit }
        ' "${f}" | head -c 110)
    fi
    [ -z "${h1}" ] && h1="(no header)"
    # Escape pipe chars so they do not break the markdown table
    echo "${h1}" | sed 's/|/\\|/g'
}

last_commit_date() {
    git log -1 --format='%ad' --date=short -- "$1" 2>/dev/null || echo "-"
}

# ----- output -----

OUT=$(mktemp)
trap 'rm -f "${OUT}"' EXIT

cat > "${OUT}" <<EOF
# Knowledge Index

> Auto-generated by \`scripts/build-knowledge-index.sh\` — refreshed on every \`Edit\`/\`Write\` to \`${KNOWLEDGE_DIR}/\` via \`.claude/hooks/post-knowledge-edit.sh\`. **Manual edits to this file will be overwritten on the next knowledge change.**
>
> Generated: $(date -u +"%Y-%m-%d %H:%M UTC")  ·  Last commit: $(git rev-parse --short HEAD 2>/dev/null || echo "?")

## Top-level docs

| File | One-line | Last modified | Size |
|---|---|---|---|
EOF

# Top-level markdown (exclude INDEX.md + README.md) sorted alphabetically
TMP_TOP=$(mktemp); trap 'rm -f "${OUT}" "${TMP_TOP}"' EXIT
find "${KNOWLEDGE}" -maxdepth 1 -name "*.md" -not -name "INDEX.md" -not -name "README.md" 2>/dev/null | sort > "${TMP_TOP}"
TOP_COUNT=0
while IFS= read -r f; do
    [ -z "${f}" ] && continue
    rel="${f#${REPO_ROOT}/}"
    link="${f#${KNOWLEDGE}/}"
    name=$(basename "${f}")
    summary=$(first_h1 "${f}")
    last=$(last_commit_date "${rel}")
    size=$(human_size "$(wc -c < "${f}" | tr -d ' ')")
    echo "| [${name}](${link}) | ${summary} | ${last} | ${size} |" >> "${OUT}"
    TOP_COUNT=$((TOP_COUNT + 1))
done < "${TMP_TOP}"

if [ "${TOP_COUNT}" -eq 0 ]; then
    echo "| _(no markdown docs yet — add one)_ | | | |" >> "${OUT}"
fi

# Top-level non-markdown (xlsx, html, pdf, etc.) — only emit section if any exist
TMP_DATA=$(mktemp); trap 'rm -f "${OUT}" "${TMP_TOP}" "${TMP_DATA}"' EXIT
find "${KNOWLEDGE}" -maxdepth 1 -type f -not -name "*.md" -not -name ".DS_Store" -not -name ".gitkeep" 2>/dev/null | sort > "${TMP_DATA}"
DATA_COUNT=$(wc -l < "${TMP_DATA}" | tr -d ' ')

if [ "${DATA_COUNT}" -gt 0 ]; then
    {
        echo ""
        echo "## Data files (non-markdown)"
        echo ""
        echo "| File | Last modified | Size |"
        echo "|---|---|---|"
    } >> "${OUT}"
    while IFS= read -r f; do
        [ -z "${f}" ] && continue
        rel="${f#${REPO_ROOT}/}"
        link="${f#${KNOWLEDGE}/}"
        name=$(basename "${f}")
        last=$(last_commit_date "${rel}")
        size=$(human_size "$(wc -c < "${f}" | tr -d ' ')")
        echo "| [${name}](${link}) | ${last} | ${size} |" >> "${OUT}"
    done < "${TMP_DATA}"
fi

# Archive listing — count only
if [ -d "${KNOWLEDGE}/archive" ]; then
    archive_count=$(find "${KNOWLEDGE}/archive" -maxdepth 1 -type f -not -name ".gitkeep" 2>/dev/null | wc -l | tr -d ' ')
    if [ "${archive_count}" -gt 0 ]; then
        {
            echo ""
            echo "## Archive"
            echo ""
            echo "[archive/](archive/) — ${archive_count} superseded docs (not indexed; explore by hand if you need historical context)."
        } >> "${OUT}"
    fi
fi

# ----- cross-references footer -----
{
    echo ""
    echo "## Cross-references"
    echo ""
    if [ -f "${KNOWLEDGE}/${CONSTITUTION_FILE}" ]; then
        echo "- **Living constitution:** [${CONSTITUTION_FILE}](${CONSTITUTION_FILE}) — single source of truth, supersedes any contradicting doc"
    fi
    if [ -d "${REPO_ROOT}/memory" ]; then
        echo "- **Working memory:** [../memory/](../memory/) — stakeholders, briefs, decisions, archive (plus optional branch-out, shadow, calibration, intel, watch)"
    fi
    if [ -f "${REPO_ROOT}/CLAUDE.md" ]; then
        echo "- **Claude instructions:** [../CLAUDE.md](../CLAUDE.md) — agent behaviour rules"
    fi
    if [ -d "${REPO_ROOT}/.claude/agents" ]; then
        agent_count=$(find "${REPO_ROOT}/.claude/agents" -maxdepth 1 -type f -name "*.md" 2>/dev/null | wc -l | tr -d ' ')
        if [ "${agent_count}" -gt 0 ]; then
            agent_list=$(find "${REPO_ROOT}/.claude/agents" -maxdepth 1 -type f -name "*.md" 2>/dev/null | sort | xargs -I{} basename {} .md | tr '\n' ',' | sed 's/,/, /g; s/, $//')
            echo "- **Custom agents:** [../.claude/agents/](../.claude/agents/) — ${agent_list}"
        fi
    fi
} >> "${OUT}"

# ----- emit -----

if [ "${DRY}" -eq 1 ]; then
    cat "${OUT}"
else
    mv "${OUT}" "${INDEX}"
    trap - EXIT
    md_count=$(grep -c '^| \[' "${INDEX}" 2>/dev/null || echo 0)
    echo "${KNOWLEDGE_DIR}/INDEX.md refreshed (${md_count} entries)" >&2
fi
