#!/usr/bin/env bash
# scripts/build-memory-map.sh
#
# Regenerate memory/MAP.md by scanning topic shards, decisions, briefs,
# stakeholders, archives. Optional sections (predictive layer, custom
# agents) only rendered if directories non-empty — per memory-architect
# MAP.template.md "_(omit section if empty)_" rule.
#
# Triggered automatically by post-memory-edit hook on Edit/Write to
# memory/topics/, memory/decisions/, memory/briefs/, memory/stakeholders/,
# memory/archive/.
#
# Idempotent — safe to re-run.
#
# Usage:
#   bash scripts/build-memory-map.sh          # write to memory/MAP.md
#   bash scripts/build-memory-map.sh --dry    # stdout only, no file write
#
# Configuration (env vars or governance.config.yaml):
#   GIOVANNI_MEMORY_DIR             default: memory
#   GIOVANNI_KNOWLEDGE_DIR          default: knowledge
#   GIOVANNI_CONSTITUTION_FILE      default: constitution.md
#   GIOVANNI_L1_FILE                default: CLAUDE_MEMORY.md  (operational L1)

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPO_ROOT="$( cd "${SCRIPT_DIR}/.." && pwd )"
MEMORY_DIR="${GIOVANNI_MEMORY_DIR:-memory}"
KNOWLEDGE_DIR="${GIOVANNI_KNOWLEDGE_DIR:-knowledge}"
CONSTITUTION_FILE="${GIOVANNI_CONSTITUTION_FILE:-constitution.md}"
L1_FILE="${GIOVANNI_L1_FILE:-CLAUDE_MEMORY.md}"

MEMORY="${REPO_ROOT}/${MEMORY_DIR}"
MAP="${MEMORY}/MAP.md"
DRY=0
[ "${1:-}" = "--dry" ] && DRY=1

if [ ! -d "${MEMORY}" ]; then
    echo "ERROR: memory dir not found: ${MEMORY}" >&2
    exit 1
fi

cd "${REPO_ROOT}"

# ----- helpers -----

# Parse a frontmatter scalar field. Returns value or empty string.
get_frontmatter_field() {
    local file="$1"
    local field="$2"
    awk -v field="${field}" '
        BEGIN { in_fm = 0 }
        /^---$/ {
            if (in_fm) { exit }
            in_fm = 1
            next
        }
        in_fm && $0 ~ "^" field ":" {
            sub("^" field ":[ \t]*", "")
            sub("[ \t]+$", "")
            print
            exit
        }
    ' "${file}"
}

last_commit_date() {
    git log -1 --format='%ad' --date=short -- "$1" 2>/dev/null || echo "-"
}

# Count files matching a glob; 0 if directory missing.
count_files() {
    local dir="$1"; shift
    local pattern="${1:-*}"
    [ -d "${dir}" ] || { echo 0; return; }
    find "${dir}" -maxdepth 1 -type f -name "${pattern}" 2>/dev/null | wc -l | tr -d ' '
}

# ----- output -----

OUT=$(mktemp)
trap 'rm -f "${OUT}"' EXIT

# ----- Header -----

cat > "${OUT}" <<EOF
# Memory MAP — navigation index

> Auto-regenerated by \`scripts/build-memory-map.sh\` on every \`Edit\`/\`Write\` to \`${MEMORY_DIR}/topics/\`, \`${MEMORY_DIR}/decisions/\`, \`${MEMORY_DIR}/briefs/\`, \`${MEMORY_DIR}/stakeholders/\`, \`${MEMORY_DIR}/archive/\`. **Manual edits will be overwritten.**
>
> Generated: $(date -u +"%Y-%m-%d %H:%M UTC")  ·  Commit: $(git rev-parse --short HEAD 2>/dev/null || echo "?")

## Live operational state

EOF

# L1 + lightweight state files
if [ -f "${MEMORY}/${L1_FILE}" ]; then
    l1_lines=$(wc -l < "${MEMORY}/${L1_FILE}" 2>/dev/null | tr -d ' ')
    echo "- [${L1_FILE}](${L1_FILE}) — current state, active blockers, this week (${l1_lines} lines)" >> "${OUT}"
fi
if [ -f "${MEMORY}/audit_state.md" ]; then
    echo "- [audit_state.md](audit_state.md) — memory hygiene state (cadence + last runs)" >> "${OUT}"
fi
if [ -f "${MEMORY}/digest_state.md" ]; then
    echo "- [digest_state.md](digest_state.md) — daily digest state" >> "${OUT}"
fi

# ----- Active topic shards -----

if [ -d "${MEMORY}/topics" ]; then
    TMP_TOPICS=$(mktemp); trap 'rm -f "${OUT}" "${TMP_TOPICS}"' EXIT
    find "${MEMORY}/topics" -maxdepth 1 -type f -name "*.md" 2>/dev/null | sort > "${TMP_TOPICS}"
    topic_count=$(wc -l < "${TMP_TOPICS}" | tr -d ' ')

    {
        echo ""
        echo "## Active topic shards (${MEMORY_DIR}/topics/)"
        echo ""
    } >> "${OUT}"

    if [ "${topic_count}" -gt 0 ]; then
        {
            echo "| Slug | Status | Last touch | Owner |"
            echo "|---|---|---|---|"
        } >> "${OUT}"
        while IFS= read -r f; do
            [ -z "${f}" ] && continue
            slug=$(get_frontmatter_field "${f}" "slug")
            status=$(get_frontmatter_field "${f}" "status")
            last_touch=$(get_frontmatter_field "${f}" "last_touch")
            owner=$(get_frontmatter_field "${f}" "owner")
            name=$(basename "${f}")
            [ -z "${slug}" ] && slug=$(basename "${f}" .md)
            [ -z "${status}" ] && status="-"
            [ -z "${last_touch}" ] && last_touch="-"
            [ -z "${owner}" ] && owner="-"
            echo "| [${slug}](topics/${name}) | ${status} | ${last_touch} | ${owner} |" >> "${OUT}"
        done < "${TMP_TOPICS}"
    else
        echo "_(no active shards yet — graduate items from L1 when they hit the criteria — see \`memory/README.md\`)_" >> "${OUT}"
    fi
fi

# ----- Resolved topic shards (only if non-empty) -----

if [ -d "${MEMORY}/topics/_resolved" ]; then
    TMP_RESOLVED=$(mktemp); trap 'rm -f "${OUT}" "${TMP_TOPICS:-/dev/null}" "${TMP_RESOLVED}"' EXIT
    find "${MEMORY}/topics/_resolved" -maxdepth 1 -type f -name "*.md" 2>/dev/null | sort > "${TMP_RESOLVED}"
    resolved_count=$(wc -l < "${TMP_RESOLVED}" | tr -d ' ')
    if [ "${resolved_count}" -gt 0 ]; then
        {
            echo ""
            echo "## Resolved topic shards (${MEMORY_DIR}/topics/_resolved/)"
            echo ""
            echo "| Slug | Resolved | Owner |"
            echo "|---|---|---|"
        } >> "${OUT}"
        while IFS= read -r f; do
            [ -z "${f}" ] && continue
            slug=$(get_frontmatter_field "${f}" "slug")
            resolved_date=$(get_frontmatter_field "${f}" "resolved_date")
            [ -z "${resolved_date}" ] && resolved_date=$(get_frontmatter_field "${f}" "last_touch")
            owner=$(get_frontmatter_field "${f}" "owner")
            name=$(basename "${f}")
            [ -z "${slug}" ] && slug=$(basename "${f}" .md)
            [ -z "${resolved_date}" ] && resolved_date="-"
            [ -z "${owner}" ] && owner="-"
            echo "| [${slug}](topics/_resolved/${name}) | ${resolved_date} | ${owner} |" >> "${OUT}"
        done < "${TMP_RESOLVED}"
    fi
fi

# ----- Canonical knowledge -----

{
    echo ""
    echo "## Canonical knowledge"
    echo ""
} >> "${OUT}"

if [ -f "${REPO_ROOT}/${KNOWLEDGE_DIR}/INDEX.md" ]; then
    echo "- [${KNOWLEDGE_DIR}/INDEX.md](../${KNOWLEDGE_DIR}/INDEX.md) — auto-generated knowledge index" >> "${OUT}"
fi
if [ -f "${REPO_ROOT}/${KNOWLEDGE_DIR}/${CONSTITUTION_FILE}" ]; then
    constitution_lines=$(wc -l < "${REPO_ROOT}/${KNOWLEDGE_DIR}/${CONSTITUTION_FILE}" | tr -d ' ')
    echo "- [${KNOWLEDGE_DIR}/${CONSTITUTION_FILE}](../${KNOWLEDGE_DIR}/${CONSTITUTION_FILE}) — single source of truth (${constitution_lines} lines)" >> "${OUT}"
fi
if [ -f "${REPO_ROOT}/CLAUDE.md" ]; then
    echo "- [CLAUDE.md](../CLAUDE.md) — agent behaviour rules" >> "${OUT}"
fi

# ----- Decision records -----

if [ -d "${MEMORY}/decisions" ]; then
    decision_count=$(count_files "${MEMORY}/decisions" "*.md")
    {
        echo ""
        echo "## Decision records (${MEMORY_DIR}/decisions/)"
        echo ""
    } >> "${OUT}"
    if [ "${decision_count}" -gt 0 ]; then
        {
            echo "| Date | Slug | Status |"
            echo "|---|---|---|"
        } >> "${OUT}"
        # Sort by filename descending (date-prefixed)
        for f in $(find "${MEMORY}/decisions" -maxdepth 1 -type f -name "*.md" 2>/dev/null | sort -r); do
            slug=$(get_frontmatter_field "${f}" "situation")
            [ -z "${slug}" ] && slug=$(get_frontmatter_field "${f}" "slug")
            status=$(get_frontmatter_field "${f}" "status")
            name=$(basename "${f}" .md)
            date=$(echo "${name}" | grep -oE '^[0-9]{4}-[0-9]{2}-[0-9]{2}' || echo "-")
            [ -z "${slug}" ] && slug=$(echo "${name}" | sed -E 's/^[0-9]{4}-[0-9]{2}-[0-9]{2}-//' )
            [ -z "${status}" ] && status="-"
            echo "| ${date} | [${slug}](decisions/${name}.md) | ${status} |" >> "${OUT}"
        done
    else
        echo "_(no decision records yet)_" >> "${OUT}"
    fi
fi

# ----- Briefs -----

if [ -d "${MEMORY}/briefs" ]; then
    brief_count=$(find "${MEMORY}/briefs" -maxdepth 1 -type f -name "*.md" -not -name "README.md" 2>/dev/null | wc -l | tr -d ' ')
    {
        echo ""
        echo "## Briefs (${MEMORY_DIR}/briefs/)"
        echo ""
    } >> "${OUT}"
    if [ "${brief_count}" -gt 0 ]; then
        {
            echo "| Date | Event slug |"
            echo "|---|---|"
        } >> "${OUT}"
        for f in $(find "${MEMORY}/briefs" -maxdepth 1 -type f -name "*.md" -not -name "README.md" 2>/dev/null | sort -r); do
            name=$(basename "${f}" .md)
            date=$(echo "${name}" | grep -oE '^[0-9]{4}-[0-9]{2}-[0-9]{2}' || echo "-")
            slug=$(echo "${name}" | sed -E 's/^[0-9]{4}-[0-9]{2}-[0-9]{2}[_-]//')
            echo "| ${date} | [${slug}](briefs/${name}.md) |" >> "${OUT}"
        done
    else
        echo "_(no briefs yet)_" >> "${OUT}"
    fi
fi

# ----- Stakeholder profiles -----

if [ -d "${MEMORY}/stakeholders" ]; then
    stake_count=$(find "${MEMORY}/stakeholders" -maxdepth 1 -type f -name "*.md" -not -name "README.md" 2>/dev/null | wc -l | tr -d ' ')
    {
        echo ""
        echo "## Stakeholder profiles (${MEMORY_DIR}/stakeholders/)"
        echo ""
    } >> "${OUT}"
    if [ "${stake_count}" -gt 0 ]; then
        echo "${stake_count} profiles. Browse [${MEMORY_DIR}/stakeholders/](stakeholders/) or grep by name." >> "${OUT}"
        echo "" >> "${OUT}"
        echo "Available:" >> "${OUT}"
        for f in $(find "${MEMORY}/stakeholders" -maxdepth 1 -type f -name "*.md" -not -name "README.md" 2>/dev/null | sort); do
            name=$(basename "${f}" .md)
            echo "- [${name}](stakeholders/${name}.md)" >> "${OUT}"
        done
    else
        echo "_(no stakeholder profiles yet)_" >> "${OUT}"
    fi
fi

# ----- Archives -----

if [ -d "${MEMORY}/archive" ]; then
    archive_count=$(find "${MEMORY}/archive" -maxdepth 1 -type f -name "*.md" 2>/dev/null | wc -l | tr -d ' ')
    if [ "${archive_count}" -gt 0 ]; then
        {
            echo ""
            echo "## Archives (${MEMORY_DIR}/archive/)"
            echo ""
            echo "| File | Last modified |"
            echo "|---|---|"
        } >> "${OUT}"
        for f in $(find "${MEMORY}/archive" -maxdepth 1 -type f -name "*.md" 2>/dev/null | sort -r); do
            name=$(basename "${f}")
            last=$(last_commit_date "${MEMORY_DIR}/archive/${name}")
            echo "| [${name}](archive/${name}) | ${last} |" >> "${OUT}"
        done
    fi
fi

# ----- Predictive / governance layer (optional; only if non-empty) -----

PREDICTIVE_LINES=""

if [ -d "${MEMORY}/branch-out" ]; then
    bo_count=$(find "${MEMORY}/branch-out" -maxdepth 1 -type f -name "*.md" 2>/dev/null | wc -l | tr -d ' ')
    if [ "${bo_count}" -gt 0 ]; then
        PREDICTIVE_LINES="${PREDICTIVE_LINES}- **${MEMORY_DIR}/branch-out/** — ${bo_count} simulation artifacts"$'\n'
    fi
fi
if [ -d "${MEMORY}/shadow" ]; then
    pending=$(find "${MEMORY}/shadow/pending" -type f -name "*.yaml" 2>/dev/null | wc -l | tr -d ' ')
    resolved=$(find "${MEMORY}/shadow/resolved" -type f -name "*.yaml" 2>/dev/null | wc -l | tr -d ' ')
    expired=$(find "${MEMORY}/shadow/expired" -type f -name "*.yaml" 2>/dev/null | wc -l | tr -d ' ')
    total_shadow=$((pending + resolved + expired))
    if [ "${total_shadow}" -gt 0 ]; then
        PREDICTIVE_LINES="${PREDICTIVE_LINES}- **${MEMORY_DIR}/shadow/** — pending: ${pending} · resolved: ${resolved} · expired: ${expired}"$'\n'
    fi
fi
if [ -d "${MEMORY}/calibration" ]; then
    cal_count=$(find "${MEMORY}/calibration" -type f 2>/dev/null | wc -l | tr -d ' ')
    if [ "${cal_count}" -gt 0 ]; then
        PREDICTIVE_LINES="${PREDICTIVE_LINES}- **${MEMORY_DIR}/calibration/** — actor scores + monthly reports"$'\n'
    fi
fi
if [ -d "${MEMORY}/audits" ]; then
    audit_count=$(find "${MEMORY}/audits" -type f -name "*.md" 2>/dev/null | wc -l | tr -d ' ')
    if [ "${audit_count}" -gt 0 ]; then
        PREDICTIVE_LINES="${PREDICTIVE_LINES}- **${MEMORY_DIR}/audits/** — ${audit_count} audit artifacts"$'\n'
    fi
fi
if [ -d "${MEMORY}/watch" ]; then
    watch_count=$(find "${MEMORY}/watch" -maxdepth 1 -type f -name "*.md" -not -name "README.md" 2>/dev/null | wc -l | tr -d ' ')
    if [ "${watch_count}" -gt 0 ]; then
        PREDICTIVE_LINES="${PREDICTIVE_LINES}- **${MEMORY_DIR}/watch/** — ${watch_count} weekly scan outputs"$'\n'
    fi
fi
if [ -d "${MEMORY}/intel" ]; then
    intel_count=$(find "${MEMORY}/intel" -type f -name "*.md" 2>/dev/null | wc -l | tr -d ' ')
    if [ "${intel_count}" -gt 0 ]; then
        PREDICTIVE_LINES="${PREDICTIVE_LINES}- **${MEMORY_DIR}/intel/** — ${intel_count} external intel artifacts"$'\n'
    fi
fi

if [ -n "${PREDICTIVE_LINES}" ]; then
    {
        echo ""
        echo "## Predictive / governance layer"
        echo ""
        printf '%s' "${PREDICTIVE_LINES}"
    } >> "${OUT}"
fi

# ----- Custom agents (only if directory non-empty) -----

if [ -d "${REPO_ROOT}/.claude/agents" ]; then
    agent_count=$(find "${REPO_ROOT}/.claude/agents" -maxdepth 1 -type f -name "*.md" 2>/dev/null | wc -l | tr -d ' ')
    if [ "${agent_count}" -gt 0 ]; then
        {
            echo ""
            echo "## Custom agents (.claude/agents/)"
            echo ""
        } >> "${OUT}"
        for f in $(find "${REPO_ROOT}/.claude/agents" -maxdepth 1 -type f -name "*.md" 2>/dev/null | sort); do
            name=$(basename "${f}" .md)
            echo "- ${name}" >> "${OUT}"
        done
    fi
fi

# ----- Static navigation footer -----

cat >> "${OUT}" <<EOF

## How to navigate

**Session start auto-loads:** ${L1_FILE} (operational shortcut) + this MAP (navigation).

**Topic-specific query → lazy load shard:**

1. Grep MAP for keywords matching user query (slug + stakeholder names + key terms)
2. Read matching shard from \`${MEMORY_DIR}/topics/<slug>.md\`
3. Follow pointers in shard frontmatter (\`related_decisions\`, \`related_briefs\`, \`related_knowledge\`) for depth

**Need history → archives + git log:**

- Resolved items archive: \`${MEMORY_DIR}/archive/<YYYY-MM>.md\`
- Per-decision audit trail: \`${MEMORY_DIR}/decisions/<date>-<slug>.md\`
- Past meeting prep: \`${MEMORY_DIR}/briefs/<date>_<event>.md\`

**Need canonical → knowledge:**

- \`${KNOWLEDGE_DIR}/${CONSTITUTION_FILE}\` is single source of truth
- \`${KNOWLEDGE_DIR}/INDEX.md\` lists all knowledge docs

**Need to write something → classify first** (see \`${MEMORY_DIR}/README.md\` "Classification rule"):

- Decision → \`${MEMORY_DIR}/decisions/\`
- Historical artifact → \`${MEMORY_DIR}/archive/\` or \`deliverables/\`
- Canonical fact → constitution patch proposal
- Operational current state → \`${L1_FILE}\` (then likely graduate to shard)
EOF

# ----- emit -----

if [ "${DRY}" -eq 1 ]; then
    cat "${OUT}"
else
    mv "${OUT}" "${MAP}"
    trap - EXIT
    topic_count=$(count_files "${MEMORY}/topics" "*.md")
    decision_count=$(count_files "${MEMORY}/decisions" "*.md")
    echo "${MEMORY_DIR}/MAP.md refreshed (topics: ${topic_count} · decisions: ${decision_count})" >&2
fi
