#!/usr/bin/env bash
# scripts/build-claude-baseline.sh — deterministic snapshot of the .claude/ surface.
#
# Why this exists: the agentic layer grows by accretion. A command added in the session
# that needed it, an agent someone wrote once, a hook from a bad afternoon. Nothing
# records the shape of the whole, so nobody notices it doubling — and an apparatus
# nobody can see whole is one nobody can prune.
#
# This file makes the shape diffable. At every full memory audit (docs/governance.md
# § Audit cadence, step 0) you diff the live surface against the committed baseline;
# every diff line is an item to explain, not a surprise:
#
#   * new file with no row in the route table      -> finding
#   * changed hash                                 -> "what changed and why"
#   * empty diff                                   -> genuinely nothing moved
#
# Usage:
#   bash scripts/build-claude-baseline.sh          # write memory/audits/claude-baseline.md
#   bash scripts/build-claude-baseline.sh --dry    # print to stdout, write nothing
#   bash scripts/build-claude-baseline.sh --dry | diff memory/audits/claude-baseline.md -
#
# Deterministic on purpose: no timestamps, no commit SHAs, LC_ALL=C sort, and
# `git hash-object` for content hashes (portable, no shasum/sha1sum dependency).
# A snapshot with a date in it diffs dirty every run and teaches you to ignore it.
set -euo pipefail
export LC_ALL=C

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

OUT="memory/audits/claude-baseline.md"
DRY=0
[ "${1:-}" = "--dry" ] && DRY=1

# `|| true` inside the substitution, not outside: pipefail turns a missing directory
# (find exits 1) into a dead script, and a fork without .claude/skills is normal.
count_files() { { find "$1" -maxdepth 1 -type f -name "$2" 2>/dev/null || true; } | wc -l | tr -d ' '; }

row() {  # path -> | path | lines | bytes | hash10 |
    local f=$1 lines bytes h
    lines=$(wc -l < "$f" | tr -d ' ')
    bytes=$(wc -c < "$f" | tr -d ' ')
    h=$(git hash-object "$f" | cut -c1-10)
    printf '| `%s` | %s | %s | `%s` |\n' "$f" "$lines" "$bytes" "$h"
}

gen() {
    local wf cm ag hk sk lrules
    wf=$(count_files .claude/workflows '*.md')
    cm=$(count_files .claude/commands '*.md')
    ag=$(count_files .claude/agents '*.md')
    hk=$(count_files .claude/hooks '*.sh')
    sk=$({ find .claude/skills -maxdepth 1 -mindepth 1 -type d 2>/dev/null || true; } | wc -l | tr -d ' ')
    lrules=$(count_files scripts/lint_rules '*.py')

    echo "# .claude/ baseline"
    echo
    echo "> Auto-generated by \`scripts/build-claude-baseline.sh\`. Regenerate at every full memory audit, after the diff has been explained (\`--dry | diff $OUT -\`). Do not edit by hand. Deterministic: no dates, no SHAs."
    echo
    echo "## Counts"
    echo
    echo "| Surface | Count |"
    echo "|---|---|"
    echo "| workflows (\`.claude/workflows/*.md\`) | $wf |"
    echo "| commands (\`.claude/commands/*.md\`) | $cm |"
    echo "| agents (\`.claude/agents/*.md\`) | $ag |"
    echo "| hooks (\`.claude/hooks/*.sh\`) | $hk |"
    echo "| skills (\`.claude/skills/*/\`) | $sk |"
    echo "| lint rules (\`scripts/lint_rules/*.py\`) | $lrules |"
    echo

    if [ -f .claude/settings.json ]; then
        echo "## settings.json hooks (event → registered commands)"
        echo
        python3 - <<'PY'
import json
try:
    h = json.load(open(".claude/settings.json")).get("hooks", {})
except Exception as e:
    print(f"- (unreadable: {e})")
    raise SystemExit(0)
for event in sorted(h):
    cmds = []
    for entry in h[event]:
        for hook in entry.get("hooks", []):
            cmd = hook.get("command")
            cmds.append(cmd.split()[-1] if cmd else hook.get("type", "?"))
    print(f"- **{event}** ({len(cmds)}): " + ", ".join(f"`{c}`" for c in sorted(cmds)))
PY
        echo
    fi

    for section in "workflows:.claude/workflows:*.md" "commands:.claude/commands:*.md" \
                   "agents:.claude/agents:*.md" "hooks:.claude/hooks:*.sh"; do
        IFS=: read -r name dir glob <<< "$section"
        [ -d "$dir" ] || continue
        echo "## $name"
        echo
        echo "| file | lines | bytes | hash |"
        echo "|---|---|---|---|"
        while IFS= read -r f; do row "$f"; done < <(find "$dir" -maxdepth 1 -type f -name "$glob" | LC_ALL=C sort)
        echo
    done

    if [ -d .claude/skills ]; then
        echo "## skills (directory → SKILL.md)"
        echo
        echo "| file | lines | bytes | hash |"
        echo "|---|---|---|---|"
        while IFS= read -r d; do
            if [ -f "$d/SKILL.md" ]; then row "$d/SKILL.md"; else printf '| `%s` | — | — | `no SKILL.md` |\n' "$d"; fi
        done < <(find .claude/skills -maxdepth 1 -mindepth 1 -type d | LC_ALL=C sort)
        echo
    fi

    echo "## root files"
    echo
    echo "| file | lines | bytes | hash |"
    echo "|---|---|---|---|"
    for f in CLAUDE.md CLAUDE.template.md .claude/settings.json docs/invariants.md scripts/lint.sh scripts/lint.py; do
        [ -f "$f" ] && row "$f"
    done
}

if [ "$DRY" = 1 ]; then
    gen
else
    mkdir -p "$(dirname "$OUT")"
    gen > "$OUT"
    echo "wrote $OUT"
fi
